### ISSUE TITLE
Upgrade osc-cl1 and osc-cl2 to odh v1.1.2

### ISSUE THREAD

**Issue by HumairAK** [open-services-group/devsecops#9]
This will require rebasing the `odh-manifests` fork to v1.1.2 for both branches and following the changes [here](https://github.com/opendatahub-io/odh-manifests/releases/tag/v1.1.2) and also run a diff, to ensure none of our existing overrides break.

**Comment by HumairAK** [comment]
@Gregory-Pereira

**Comment by HumairAK** [comment]
We do not want to rebase, otherwise we will end up changing the sha on our commits. @harshad16 can you expand here on how rhods does it (i.e. cherrypick commits)?

**Comment by harshad16** [comment]
Rebasing commits from upstream, normally changes the commit sha of the latest commit (which are not present in upstream).
This implies that the commit is added with commiter/co-author by whoever did the rebase.

As there would be work done in-branch and multiple commits can differ from upstream.
The RHODS team themselves have adapted to use the cherry-pick of the commit from upstream instead of rebasing.

The cherry-picked commit is added with the prefix `[UPSTREAM <sha>]` in the commit message.
In this way, the developer can differentiate on what work is from upstream and what is from the development branch.
ex: https://github.com/red-hat-data-services/odh-manifests/commit/5ce54b460e03faa1c1109b2dcc19747d59afcdf6

there is an automation task:
https://github.com/AICoE/aicoe-ci/blob/master/tasks/z-stream-update-rhods-task.yaml
which can perform the action.
